name: StatTracker
version: '1.0-SNAPSHOT'
main: org.dimaserver.statTracker.StatTracker
api-version: '1.21'
authors: [ Jevk ]
description: Custom tab menu for Dima's Minecraft server.
commands:
  link:
    description: Link your Minecraft account to your Discord or Twitch account.
    usage: /link [discord|twitch] <userID>

  unlink:
    description: Unlink your Minecraft account from your Discord or Twitch account.
    usage: /unlink [discord|twitch]

